### ISSUE TITLE
require.extensions is not defined on node v8.x.x

### ISSUE THREAD

**Issue by phra** [mikeal/r2#18]
hi,

when i try to use r2 with node v8.x.x i got this error: TypeError: require.extensions.hasOwnProperty is not a function
you can reproduce the issue here: https://runkit.com/phra/r2-require-extensions

**Comment by thechriswalker** [comment]
That's not the `r2` you are looking for... https://www.npmjs.com/package/r2 is something totally different (https://github.com/3vot/clay by the look of it - must have been published as r2 at some point...)

**Comment by phra** [comment]
uhm.. so `r2` it's not a good name.. we already suffered from typo squatting on npm.. no need for already used package names..
