### ISSUE TITLE
rename package because is already taken on NPM

### ISSUE THREAD

**Issue by phra** [mikeal/r2#20]
Hi,

i was losing a lot of time in order to use r2 because i was getting a lot of problems. as @thechriswalker has noted,  the `r2` [package on NPM](https://www.npmjs.com/package/r2) is another one and so it creates confusion.

imho it's better if we find another name for this package that is free on NPM.

**Comment by jackwilsdon** [comment]
This is probably better as a comment on #7.

**Comment by mikeal** [comment]
The package is not active, I've emailed the author and npm asking for a transfer.

**Comment by phra** [comment]
@mikeal keep in mind that the old `r2` is already published on the existing cdn based on npm registry, e.g. https://unpkg.com/r2@1.0.0/index.js

**Comment by mreinstein** [comment]
@mikeal I'm curious, why not just make this request v3 ? semver will prevent this from breaking stuff, and we get to keep the same great original module name.

**Comment by mikeal** [comment]
Published as `r2`. https://www.npmjs.com/package/r2
