### ISSUE TITLE
Add peer-dependency for isomorphic-fetch or some equal library

### ISSUE THREAD

**Issue by iDuuck** [mikeal/r2#27]
Title says all. No mention about anything in the README nor in the package.json (except from `node-fetch` which is a dependency.

**Comment by iDuuck** [comment]
Another solution would be to offer a plugin system: We would have the base system that uses the fetch system, but the user would be able to plugin some different adapter to the r2 system.

This specific module structure:
- r2 (by default uses fetch)
- r2-adapter-fetch (used by default)
- r2-adapter-axios
- ...

**Comment by gr2m** [comment]
obsolete as per node-fetch@2.0.0
