### ISSUE TITLE
Update require-dir (to fix node 8 issues)

### ISSUE THREAD

**Issue by mikemaccana** [mikeal/r2#35]
node_modules\require-dir\index.js:93
    if (!require.extensions.hasOwnProperty(ext)) {
    TypeError: require.extensions.hasOwnProperty is not a function

Already fixed in https://github.com/aseemk/requireDir/issues/45. `require-dir` just needs an update

**Comment by BigMurry** [comment]
I've encountered the same issue.

**Comment by mikeal** [comment]
Yup, that's the old r2 before I got the package name. Try a new install :)
