### ISSUE TITLE
Is it possible to access connection properties in r2?

### ISSUE THREAD

**Issue by mikemaccana** [mikeal/r2#36]
With the old request, I can use streams to handle the 'response' event, and get connection properties because the HTTP connection is still open.

@Mikeal how is this handled in r2, if it all? I know there's some conceptual overlap between promises and streams so I'm not sure if r2 can do this, can't do this,. or there's a better way of accessing connection properties.

	req.on('response', function (res) {
		var certificate = res.req.connection.getPeerCertificate && res.req.connection.getPeerCertificate(true)

Thanks!

**Comment by mikeal** [comment]
That's a specific Node.js feature and r2 is built on top of the fetch API so this kind of stuff isn't exposed in a consistent way, you'd have to dig through the Fetch polyfill to find it.

**Comment by mikemaccana** [comment]
Fair enough, I'll keep on `request` for now.
