### ISSUE TITLE
How to access response status code

### ISSUE THREAD

**Issue by ivan-kleshnin** [mikeal/r2#43]
I'm surprised it's not covered in docs or tests.

```js
r2("http://localhost:3000/500").json
  .catch(e => {
    console.log("e:", e) // not getting there even for 500
  })
  .then(x => {
    console.log("x:", x) // x is response.body here, how to get response.status?
  })
```

**Comment by Sigmus** [comment]
Have you tried replacing ```.json``` with ```.response``` or removing ```.json```?

**Comment by ivan-kleshnin** [comment]
Yep, it helps. For now, I'm staying will Axios, however, because it's smaller (which is weird, because Axios wraps XMLHttpRequest API, not fetch API).

**Comment by mikeal** [comment]
Maybe it's the Buffer polyfill?

**Comment by ivan-kleshnin** [comment]
Perhaps. Or something about Unicode support.

**Comment by geetotes** [comment]
For anyone else trying to figure out how to access the response status, you can access it like:

```
await r2(url, { headers }).response.then(r => {
      console.log(r.ok);
      console.log(r.statusText);
      console.log(r.status);
    });
```

For an endpoint that is a returns a 401 status, the output will look like this:
```
false
Unauthorized
401
```

The response object is a [fetch response](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful)
