### ISSUE TITLE
Proxy support ?

### ISSUE THREAD

**Issue by 0gust1** [mikeal/r2#44]
One thing I liked with request, it's support of env vars for managing proxy behavior (https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables).
It's **very** convenient, especially if you work under a corporate proxy 😢 , and the production is not.

Is there something like that planned for r2 ?

**Comment by mikeal** [comment]
r2 is intended more for browser focused use cases, so probably not since none of that information is available in the browser directly.

i would consider adding support in `bent()` though.
