### ISSUE TITLE
can the dependence of node-fetch  use the 1.x ?

### ISSUE THREAD

**Issue by beginnor** [mikeal/r2#46]
I find the default dependence of node-fetch is  2.x ,it's a alpha version , and i find in crawling some website (eg. https://www.baidu.com) ,the node-fetch 2.x inner function clone will in error that cannot output any result  and not throw any error. 
I  test in the node-fetch 1.x ，it will ok .

3ks

**Comment by gr2m** [comment]
the stable version of node-fetch@2.0.0 is release, we’ll upgrade to it shortly
