### ISSUE TITLE
make-fetch-happen instead of node-fetch

### ISSUE THREAD

**Issue by Kikobeats** [mikeal/r2#5]
Hey,

I want to introduce you [make-fetch-happen](https://github.com/zkat/make-fetch-happen).

It's similar to node-fetch but more powerful in terms of retries and additional features in the backend side.

Do you think could be a good dependency to be used for this project?

**Comment by mikeal** [comment]
Does this go beyond what is part of the Fetch spec?

I'd like to use whatever is closest to the browser implementation right now.
