### ISSUE TITLE
Enable promise dependency injection (just like node-fetch)

### ISSUE THREAD

**Issue by richardpringle** [mikeal/r2#50]
`node-fetch` allows Promise dependency injection (if you like using bluebird for example). It would be great if we could do the same thing with this wrapper.

**Comment by gr2m** [comment]
I talked to @timothyGu about the ability to set a custom promise on `node-fetch`. They are not very happy with the implementation, they will probably remove it in future, so I don’t think that we should add it

**Comment by richardpringle** [comment]
>They are not very happy with the implementation

@gr2m, I would love a better explanation of why they weren't/aren't happy with their implementation.

I'm trying to contribute and improve this package. While I get that my idea of what is/isn't an improvement may differ from the opinion of the collaborators, it would be nice to give an explanation beyond "some other guy isn't happy with their implementation of the same feature, so we won't adopt that same implementation".

Libraries like [BluebirdJS](https://github.com/petkaantonov/bluebird) are both faster than native promises and come with a lot of extra utility functions. `tap` and `tapCatch` are the two that I'm most interested in personally as they provide a very clean API for logging.

I'm sure @TimothyGu has some great reasons as to why the disadvantages of setting your own promise dependencies outweigh the extra speed and utility of the widely used `BluebirdJS`, but without that explanation, this looks like a decision was made here without any real justification.

**Comment by ljharb** [comment]
It’s worth noting that they’re primarily faster by violating the language spec (altho not A+). Can’t you wrap the returned promise in your library of choice?

**Comment by richardpringle** [comment]
@ljharb, I think my real solution is to just use node-fetch directly.

>...violating the language spec

Thanks, I'll look into that further.
