### ISSUE TITLE
No package description

### ISSUE THREAD

**Issue by ChalkPE** [mikeal/r2#59]
[It looks so weird](https://github.com/mikeal/r2/blob/master/package.json#L4)
![screenshot from 2018-04-05 20-50-57](https://user-images.githubusercontent.com/9481405/38364330-1e0a0c7c-3913-11e8-9efa-88d21a5a9a32.png)

**Comment by gr2m** [comment]
Could you send a pull request setting it to

> HTTP client. Spiritual successor to request.

🙏

**Comment by gr2m** [comment]
oops nevermind :)
