### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by radare** [mikeal/r2#7]
i'm the only r2 in this place

**Comment by NeiPCs** [comment]
I prefer request2 instead of r2.
It also direct refer to request library, which this one suppose to replace.

**Comment by ljharb** [comment]
r2 is a well-known LTR CSS converter https://github.com/ded/R2, fwiw

**Comment by DiegoRBaquero** [comment]
I have `rz` and `sr` npm packages available. For this or any project who requires the name.

**Comment by dagman** [comment]
maybe **rqst**?

**Comment by chrishaff** [comment]
fetchquest

**Comment by jeasonstudio** [comment]
How about `req2`

**Comment by qaisjp** [comment]
How about `potato`

**Comment by thechriswalker** [comment]
@qaisjp unfortunately `potato` is taken on npm... :( 
https://www.npmjs.com/package/potato

**Comment by aganglada** [comment]
refetch

**Comment by qaisjp** [comment]
What about `pota2o`

**Comment by fega** [comment]
r2q2 ¿?

**Comment by JamesMGreene** [comment]
> refetch

Already taken. 😞

**Comment by JamesMGreene** [comment]
> How about `req2`

Already taken.

**Comment by JamesMGreene** [comment]
> I prefer request2 instead of r2.

`And `request2` is already taken as well.

**Comment by JamesMGreene** [comment]
> maybe **rqst**?

Already taken.

**Comment by JamesMGreene** [comment]
So, of all the suggestions here, the only ones currently available on NPM are:
 - `fetchquest`
 - `r2q2`

I'll also throw in a few other available ones:
 - `reqfetch`
 - `fetchreq`

**Comment by yoavmmn** [comment]
what about `rq2`? it's available on NPM

**Comment by refack** [comment]
radquest
(rad is always rad, but also loosely based on http://www.dictionary.com/browse/red-)

**Comment by JamesMGreene** [comment]
Also: `restquest`

**Comment by gruhn** [comment]
or maybe `roquest` 

__ro__ [seems to mean](https://en.m.wiktionary.org/wiki/ro#Javanese) __two__ in Javanese, which is kind of cool I think, since it's a JavaScript libary

**Comment by gruhn** [comment]
or maybe `roquest` 

__ro__ [seems to mean](https://en.m.wiktionary.org/wiki/ro#Javanese) __two__ in Javanese, which is kind of cool I think, since it's a JavaScript libary

**Comment by crock** [comment]
Keep the name the same, r2 is fine.

**Comment by shimondoodkin** [comment]
I prefer request2.
My ideas:
mikerequest
richrequest
requester 
request-tool

**Comment by yoavmmn** [comment]
The problem is that it isn’t available on NPM. @mikeal contacted the owner of the current(not active) r2 package on NPM asking for a transfer.
Another problem with the name is that `r2` is a well known LTR CSS converter. Look at the discussion above.

**Comment by fega** [comment]
or r-2??

**Comment by lirantal** [comment]
for the record, this is the best thread going on right now in github 😆

**Comment by zenflow** [comment]
It seems like many people prefer "request2" (but as @JamesMGreene pointed out, that is taken)

*(I also think it would be a great name, as it is descriptive and seems to refer to the original package.)*

**So** what about "request-2"? It has all the pros of "request2" but is available on npm...

**Comment by lirantal** [comment]
what about scoped packages? this way you can choose whatever name you want and have the prestige of your own organization :-)

**Comment by shimondoodkin** [comment]
How about request3 request4 ...

**Comment by JafarAkhondali** [comment]
How about `re-request` ? :neutral_face: 
Thanks for your amazing job, But please specify the package name in readme of repo. I lost a lot of time finding package name, I'm sure other people will do same.

**Comment by ricardosw** [comment]
`request-2` seems the best. Also, how about `2quest` or `toquest`?

**Comment by qaisjp** [comment]
What about: potatothisthingisnotbeingrenamedpleasestoppleasepleaseplease

**Comment by finalclass** [comment]
rquest

**Comment by mattbrunetti** [comment]
This may be an instance of [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding).

@mikeal If you have no interest in renaming this please say so and save everyone the energy.

*Personally I think `request-2` > `r2` as it has some semantic significance, but really it's not of utmost importance*

**Comment by qaisjp** [comment]
@mattbrunetti The author of this repository has not commented here, so it's not like he's deliberately trying to mess with all of you.

In the end, it's just a damn name..

**Comment by mattbrunetti** [comment]
@qaisjp true. I guess you could take that to mean "i don't care"

**Comment by mikeal** [comment]
Published as `r2` https://www.npmjs.com/package/r2
